export const ENV = {
  appId: process.env.VITE_APP_ID ?? "aerion-control-plane",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  nodeAgentUrl: process.env.AERION_NODE_AGENT_URL ?? "",
  nodeAgentToken: process.env.AERION_NODE_AGENT_TOKEN ?? "",
  publicAppUrl: process.env.PUBLIC_APP_URL ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  mailFrom: process.env.MAIL_FROM ?? "Aerion <login@example.com>",
};
